### ISSUE TITLE
Publish sdkgen as a npm package, if possible

### ISSUE THREAD

**Issue by vhfmag** [cubos/sdkgen#16]
## Motivation
Currently, sdkgen-based API projects use a docker container for compiling the sdkgen files on CI, and compile them by hand locally. There are two main issues with that:
- It's hard to attach a project to a specific version of sdkgen (specially, it's hard to work with projects using different versions of it)
- It's hard to integrate with tools like TypeScript and Webpack and therefore hard to automate (current workaround is to include a bash script that assumes the sdkgen source code is in a specific location and up to date) 

## Proposed solution
Libraries like node-sass compile their binaries from languages like C on post-install. A package for sdkgen would solve versioning and allow better tooling:
- A sdkgen-loader for webpack would prevent developers from working on out-of-date APIs
- So would a typescript plug-in that allowed to directly import sdkgen files and have niceties such as auto completion on modern editors

## Possible issues
- I couldn't found any example of npm packages compiling binaries with crystal, so it's feasibility is yet to be evaluated

**Comment by lbguilherme** [comment]
Required for this: Publish linux and mac pre-compiled binaries with all dependencies contained in itself. This way a NPM package can be created just like SASS

**Comment by vhfmag** [comment]
Superseded by #24
