### ISSUE TITLE
Convert web client target to ESModules to optimize bundle size

### ISSUE THREAD

**Issue by vhfmag** [cubos/sdkgen#20]
**Rationale**: Currently, the web client target generates a single file. If it generated a common module and a module per endpoint, bundle size could be hugely optimized by clients using modern bundlers, like webpack, parcel & rollup.

**Implementation details**: It would still be necessary to generate a single file module for compatibility with CommonJS, and it could be done by bundling the ESModule version. The CommonJS version could be exposed on package.json's `main` field, while the ESModule version could be expose in its `module` field (it's still a [proposed field](https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md), but is recognized by most bundlers).

Objections? Thoughts?

**Comment by lbguilherme** [comment]
I worry about the overhead when 90% of the functions are used. How much a bundler will be able to compress that? Most of them add some code around modules, so this code might end up repeated a lot.

Also, we need to rework the generator to support multiple files

**Comment by vhfmag** [comment]
If the repetitive parts (e.g. the validators) were dynamic, there would be little overhead that I can think of. Something like [io-ts](https://bundlephobia.com/result?p=io-ts@1.1.2) for validation would do the job, be lightweight (5kb) and integrate well with our Typescript stack. So my point is: let's dry out as much repetitive code as we can and see how well it plays with tree-shaking.

I guess I need to actually implement a proposal to meet the issues that would come with that. Will do so eventually, after sdkgen is migrated to Typescript.

**Comment by vhfmag** [comment]
Actually, endpoints are exported already with ESModule syntax to the api.ts file. It's the api.js file that is bundled as CommonJS. We could generate a separate file (`api.mjs`, for compatibility with Node?) bundled as a ESModule and expose it on the main field of package.json. It's a simpler and easier to implement solution, so I'll open another issue proposing that and close this one.

**Comment by lbguilherme** [comment]
why close? On 19 May 2018 13:53, Victor Magalhães <notifications@github.com> wrote:Closed #20.

**Comment by vhfmag** [comment]
Generating multiple files would be a great amount of work and can be avoided by generating and exposing a single file ESModule version of the API. See #29 and #28.

**Comment by dygufa** [comment]
We still need to be able to generate multiple files in order to generate real npm packages for examples. The sdkgen should be able to generate a npm package without a second step (build_and_publish.sh)

**Comment by vhfmag** [comment]
I'm not sure I understood, do you mean sdkgen should (be able to) output the package as a directory instead of publishing it itself? Why that?
Anyway, if there's the need to generate a multi-file target for reasons others than those discussed in this issue, I think the discussion should be moved to its own issue.

**Comment by dygufa** [comment]
I agree with you that this is not the issue to have the discussion about the multiple file thing. 
But yes, the sdkgen should output a package.
Nowadays the sdkgen output a file that have no meaning unless you use the build_and_publish.sh script, it doesn't make much sense. It should output the npm package that should be published by the CI itself or by a publish.sh script.
I don't think the publish process should be inside the sdkgen itself. 
Besides that the documentation target would also need that, no?
